### ISSUE TITLE
Originate without code 

### ISSUE THREAD

**Issue by talbeerysec** [AndrewKishino/sotez#48]
Seems like calling originate without contract code does not work
```
const res = await client.originate({
        balance: amount,
        spendable: true,
        delegatable: true,
        delegate: null
    });
```

to work around I added the following code
```
if (code || init) {

      if (typeof code === 'string') {
        _code = utility.ml2mic(code);
      } else {
        _code = code;
      }

      if (typeof init === 'string') {
        _init = utility.sexp2mic(init);
      } else {
        _init = init;
      }

      script = {
        code: _code,
        storage: _init,
      };
    }

```
see: https://github.com/KZen-networks/tezos-thresh-wallet/commit/f92cb36d7ac7f62fb2c74355f52f9f00cd77f516#diff-11123b687d7b7adfe15947b2cdea46d4

**Comment by AndrewKishino** [comment]
This was mostly as designed since the new protocol upgrade will require any originated contract to be created with contract code. In this case, you can still use the `account` method which doesn't require contract code when originating. Depending on how the protocol upgrade goes, `account` may need to be deprecated in favor of only using `originate`. I'm also working on adding error handling to most of the library to make things more clear.

**Comment by talbeerysec** [comment]
` account` did the magic. Thanks!
