### ISSUE TITLE
mutez option works backwards

### ISSUE THREAD

**Issue by CherryDT** [AndrewKishino/sotez#62]
If I misunderstood something here then please correct me, but for me it seems that the `mutez` flag works backwards: It says it should be specified if the input is given in mutez, and it's false by default, so I'd assume that means that the input is by default in tez.

However, that doesn't seem the case, it seems the opposite: Sending an amount of `'1000'` sends 0.001 tez and not 1000 tez, unless setting `mutez` to _`true`_!

**Comment by AndrewKishino** [comment]
You're right that it is somewhat confusing. I am going to push a change to allow you define this when initializing sotez since you most likely wont want to switch between different representations of your inputs.
```
const sotez = new Sotez('https://127.0.0.1:8732', 'main', { defaultFee: 1275, useMutez: false });
```
Default value for `useMutez` is `true`, which means that functions will use mutez values for your amounts (such as having to input `1000000` in order to send 1 tez). Otherwise if you want to use tez values, you can set `useMutez` to `false`.

I think this is the safer option as it will be harder to "accidentally" over send the amount you are intending.
